eureka:
  client:
    service-url:
      defaultZone: http://localhost:9101/eureka/
server:
  port: 9107
spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          #配置git url
          uri: https://github.com/xlsbz/cloud-config



